theme: minima
title: Subspace Systems
tagline: A systems and software contracting and consulting firm
description: Subspace Systems is a consulting and contracting firm specializing in software and systems architecture, particularly in aerospace and embedded systems.
url: https://subspacesystems.com
baseurl: ""
author:
  type: Organization
  name: Subspace Systems
  email: webmaster@subspacesystems.com

sass:
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

google_analytics: G-44XSHHD2C1

paginate: 5
paginate_path: "/blog/page:num/"
