theme: minima
title: Subspace Systems
description: Subspace Systems is a consulting firm specializing in software and systems architecture, particularly in aerospace and embedded systems.

sass:
  sass_dir: _sass
