theme: jekyll-theme-hacker
title: Subspace Systems - Software & Systems Architecture
description: Subspace Systems is a consulting firm specializing in software and systems architecture, particularly in aerospace and embedded systems.

